services:

  # ==========================================
  # PHP 8.3.6
  # ==========================================
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: gestion_reservation_app

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - reservation_network


  # ==========================================
  # NGINX
  # ==========================================
  nginx:
    image: nginx:alpine

    container_name: gestion_reservation_nginx

    ports:
      - "8080:80"

    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - app

    networks:
      - reservation_network


  # ==========================================
  # MYSQL
  # ==========================================
  mysql:
    image: mysql:8.0

    container_name: gestion_reservation_mysql

    environment:
      MYSQL_DATABASE: reservation_salles
      MYSQL_USER: root_dev
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - reservation_network


# ==========================================
# VOLUME MYSQL
# ==========================================
volumes:
  mysql_data:


# ==========================================
# NETWORK
# ==========================================
networks:
  reservation_network:
    driver: bridge